openapi: 3.0.0
info:
  title: Sample API
  description: >-
    Optional multiline or single-line description in`<br>`
    [CommonMark](http://commonmark.org/help/) or HTML.
  version: 0.1.9
servers:
  - url: 'http://api.edorkar.test/api'
    description: bangoshop Test Server
  - url: 'http://staging-api.example.com'
    description: 'Optional server description, e.g. Internal staging server for testing'



paths:
  /login:
    post:
      summary: Get User Login Token.
      requestBody:
        $ref: '#/components/requestBodies/phoneLogin'

      responses:
        '200':
          description: A JSON array of user names
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '401':
          description: Unauthorized but user was found on the server and credential is fine
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseUnAuthenticated'





components:
  schemas:
    User:
      properties:
        id:
          type: integer
        name:
          type: string
        email:
          type: string
        joinDate:
          type: string
        token:
          type: string

    ResponseAuthFailure:
      properties:
        meta:
          type: object
          properties:
            AuthFailMessage:
              type: string

    ResponseUnAuthenticated:
      allOf:
        - properties:
            status:
              type: integer
              example: 401
        - $ref: '#/components/schemas/ResponseAuthFailure'





  requestBodies:
    login:
      description: A JSON object containing pet information
      required: true
      content:
        application/json:
          schema:
            type: object
            properties:
              phone:
                type: string
              password:
                type: string
          example:
            email: gdnayeem1996@gmail.com
            password: '12345678'
    phoneLogin:
      description: A JSON object containing pet information
      required: true
      content:
        application/json:
          schema:
            type: object
            properties:
              phone:
                type: string
              password:
                type: string
          example:
            phone: 01836983974
            password: '12345678'
