openapi: 3.0.0
info:
  title: Sample API
  description: >-
    Optional multiline or single-line description in
    [CommonMark](http://commonmark.org/help/) or HTML.
  version: 0.1.9
servers:
  - url: 'http://api.edorkar.test/api'
    description: bangoshop Test Server
  - url: 'http://staging-api.example.com'
    description: 'Optional server description, e.g. Internal staging server for testing'
paths:
  /login:
    post:
      summary: Get User Login Token.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginRequest'
      responses:
        '200':
          description: A JSON array of user names
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Login'
components:
  schemas:
    User:
      properties:
        id:
          type: integer
        name:
          type: string
      required:
        - id
        - name
    Login:
      properties:
        id:
          type: integer
        name:
          type: string
        email:
          type: string
        joinDate:
          type: string
        token:
          type: string
    LoginRequest:
      properties:
        email:
          type: string
        password:
          type: string
  requestBodies:
    login:
      description: A JSON object containing pet information
      required: true
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/LoginRequest'
          example:
            email: gdnayeem1996@gmail.com
            password: '12345678'
